name: Deploy Contracts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # مرحله نصب پکیج‌ها با قدرتِ بالا
      - name: Install dependencies
        run: |
          npm install
          npm install @openzeppelin/contracts --save-dev

      # کامپایلِ قراردادها برای اینکه مطمئن شیم OpenZeppelin شناسایی شد
      - name: Compile Contracts
        run: npx hardhat compile

      # دیپلوی نهایی
      - name: Deploy to Teqoin
        run: npx hardhat run scripts/deploy.cjs --network teqoinTestnet
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          TEQOIN_RPC_URL: ${{ secrets.TEQOIN_RPC_URL }}
